[game]
fast_mode = true
number_of_arenas = 10
train = true
episodes_number = 10
folder_path = 'assets/bts/derk' # folder where the player will be saved
starting_config = 'dummy.json'
bt_best_player_name = 'trial.json'

[bt_config]
elitism = true
number_of_elites = 3
crossover = true
mutation = true
mutation_rate = 0.2
crossover_rate = 0.2
no_big_trees = 20
initial_population = 'random'
mu_lambda_strategy = 'plus'
selection_strategy = 'hall_of_fame'
tournament_size = 5
parents_proportion = 0.5
all_mutations = false
monitor = true
draw_best = false
[reward-function]
damageEnemyStatue = 5
damageEnemyUnit = 5
killEnemyStatue = 5
killEnemyUnit = 5
healFriendlyStatue = 3
healTeammate1 = 2
healTeammate2 = 2
timeSpentHomeBase = 0
timeSpentHomeTerritory = 0
timeSpentAwayTerritory = 0
timeSpentAwayBase = 0
damageTaken = -1
friendlyFire = -3
healEnemy = -3
fallDamageTaken = -1
statueDamageTaken = -3
manualBonus = 0
victory = 5
loss = -5
tie = 0
teamSpirit = 0
timeScaling = 0.4