[game]
# fast_mode = true
# number_of_arenas = 10
# train = true
# episodes_number = 10
fast_mode = false
number_of_arenas = 1
train = false
episodes_number = 1
neat_config = './configs/q_learning/melee_weapon_neat.ini'
weights_path = './weights/q_learning/melee_weapon.pkl'

[reward-function]
damageEnemyStatue = 5
damageEnemyUnit = 5
killEnemyStatue = 5
killEnemyUnit = 5
healFriendlyStatue = 0
healTeammate1 = 0
healTeammate2 = 0
timeSpentHomeBase = 0
timeSpentHomeTerritory = 0
timeSpentAwayTerritory = 0
timeSpentAwayBase = 0
damageTaken = -1
friendlyFire = -3
healEnemy = 0
fallDamageTaken = -3
statueDamageTaken = -3
manualBonus = 0
victory = 5
loss = -5
tie = 0
teamSpirit = 0
timeScaling = 0.4

[network_input]
Hitpoints = true
Ability0Ready = true
FriendStatueDistance = true
FriendStatueAngle = true
Friend1Distance = true
Friend1Angle = true
Friend2Distance = true
Friend2Angle = true
EnemyStatueDistance = true
EnemyStatueAngle = true
Enemy1Distance = true
Enemy1Angle = true
Enemy2Distance = true
Enemy2Angle = true
Enemy3Distance = true
Enemy3Angle = true
HasFocus = true
FocusRelativeRotation = true
FocusFacingUs = true
FocusFocusingBack = true
FocusHitpoints = true
Ability1Ready = true
Ability2Ready = true
FocusDazed = true
FocusCrippled = true
HeightFront1 = true
HeightFront5 = true
HeightBack2 = true
PositionLeftRight = true
PositionUpDown = true
Stuck = true
UnusedSense31 = true
HasTalons = true
HasBloodClaws = true
HasCleavers = true
HasCripplers = true
HasHealingGland = true
HasVampireGland = true
HasFrogLegs = true
HasPistol = true
HasMagnum = true
HasBlaster = true
HasParalyzingDart = true
HasIronBubblegum = true
HasHeliumBubblegum = true
HasShell = true
HasTrombone = true
FocusHasTalons = true
FocusHasBloodClaws = true
FocusHasCleavers = true
FocusHasCripplers = true
FocusHasHealingGland = true
FocusHasVampireGland = true
FocusHasFrogLegs = true
FocusHasPistol = true
FocusHasMagnum = true
FocusHasBlaster = true
FocusHasParalyzingDart = true
FocusHasIronBubblegum = true
FocusHasHeliumBubblegum = true
FocusHasShell = true
FocusHasTrombone = true
UnusedExtraSense30 = true
UnusedExtraSense31 = true

[[players]]
path = 'q_learning_nn_neat'
name = 'DerkQLearningNEATPlayer'
verbose = false
actions_space = "ranged_weapon"
movement_split = 3
rotation_split = 3
chase_focus_split = 3

[[players]]
path = 'q_learning_nn_neat'
name = 'DerkQLearningNEATPlayer'
verbose = false
actions_space = "ranged_weapon"
movement_split = 3
rotation_split = 3
chase_focus_split = 3
