[game]
fast_mode = true
number_of_arenas = 1
train = true
episodes_number = 5
bt_best_player_name = 'killer2.json'

[reward-function]
damageEnemyStatue = 10
damageEnemyUnit = 30
killEnemyStatue = 30
killEnemyUnit = 50
healFriendlyStatue = 10
healTeammate1 = 0
healTeammate2 = 0
timeSpentHomeBase = 0
timeSpentHomeTerritory = 0
timeSpentAwayTerritory = 0
timeSpentAwayBase = 0
damageTaken = 0
friendlyFire = -10
healEnemy = -10
fallDamageTaken = 2500
statueDamageTaken = -15
manualBonus = 0
victory = 2000
loss = -2000
tie = 0
teamSpirit = 0
timeScaling = 0.5

[bt_config]
elitism = true
number_of_elites = 2
crossover = true
mutation = true
mutation_rate = 0.2
tournament_size = 3