[game]
fast_mode = true
number_of_arenas = 5
train = true
episodes_number = 5
bt_best_player_name = 'perfection.json'

[reward-function]
damageEnemyStatue = 1
damageEnemyUnit = 1
killEnemyStatue = 100
killEnemyUnit = 100
healFriendlyStatue = 1
healTeammate1 = 1
healTeammate2 = 1
timeSpentHomeBase = 0
timeSpentHomeTerritory = 0
timeSpentAwayTerritory = 1
timeSpentAwayBase = 1
damageTaken = 0
friendlyFire = -5
healEnemy = -2
fallDamageTaken = -500
statueDamageTaken = -10
manualBonus = 0
victory = 800
loss = -800
tie = 0
teamSpirit = 0
timeScaling = 0.5

[bt_config]
elitism = true
number_of_elites = 6
crossover = true
mutation = true
mutation_rate = 0.2
tournament_size = 3