[game]
fast_mode = true
number_of_arenas = 10
train = true
episodes_number = 30
neat_config = './configs/NEAT_NN.ini'

[reward-function]
damageEnemyStatue = 0
damageEnemyUnit = 1
killEnemyStatue = 0
killEnemyUnit = 1
healFriendlyStatue = 0
healTeammate1 = 1
healTeammate2 = 1
timeSpentHomeBase = 0
timeSpentHomeTerritory = 0
timeSpentAwayTerritory = 0
timeSpentAwayBase = 0
damageTaken = -1
friendlyFire = -10
healEnemy = -1
fallDamageTaken = 0
statueDamageTaken = 0
manualBonus = 0
victory = 1
loss = -1
tie = 0
teamSpirit = 0
timeScaling = 0

[network_input]
Hitpoints = true
Ability0Ready = false
FriendStatueDistance = false
FriendStatueAngle = false
Friend1Distance = false
Friend1Angle = false
Friend2Distance = false
Friend2Angle = false
EnemyStatueDistance = false
EnemyStatueAngle = false
Enemy1Distance = true
Enemy1Angle = true
Enemy2Distance = true
Enemy2Angle = true
Enemy3Distance = true
Enemy3Angle = true
HasFocus = true
FocusRelativeRotation = false
FocusFacingUs = false
FocusFocusingBack = false
FocusHitpoints = true
Ability1Ready = false
Ability2Ready = false
FocusDazed = false
FocusCrippled = false
HeightFront1 = false
HeightFront5 = false
HeightBack2 = false
PositionLeftRight = false
PositionUpDown = false
Stuck = false
UnusedSense31 = false
HasTalons = false
HasBloodClaws = false
HasCleavers = false
HasCripplers = false
HasHealingGland = false
HasVampireGland = false
HasFrogLegs = false
HasPistol = false
HasMagnum = false
HasBlaster = false
HasParalyzingDart = false
HasIronBubblegum = false
HasHeliumBubblegum = false
HasShell = false
HasTrombone = false
FocusHasTalons = false
FocusHasBloodClaws = false
FocusHasCleavers = false
FocusHasCripplers = false
FocusHasHealingGland = false
FocusHasVampireGland = false
FocusHasFrogLegs = false
FocusHasPistol = false
FocusHasMagnum = false
FocusHasBlaster = false
FocusHasParalyzingDart = false
FocusHasIronBubblegum = false
FocusHasHeliumBubblegum = false
FocusHasShell = false
FocusHasTrombone = false
UnusedExtraSense30 = false
UnusedExtraSense31 = false

[[players]]
path = 'bot'
name = 'DerkPlayer'
test = 5

[[players]]
path = 'bot'
name = 'DerkPlayer'
test = 7
