[game]
fast_mode = false
number_of_arenas = 2
train = true
episodes_number = 5

[reward-function]
damageEnemyStatue = 4
damageEnemyUnit = 2
killEnemyStatue = 4
killEnemyUnit = 2
healFriendlyStatue = 1
healTeammate1 = 2
healTeammate2 = 2
timeSpentHomeBase = 0
timeSpentHomeTerritory = 0
timeSpentAwayTerritory = 0
timeSpentAwayBase = 0
damageTaken = -1
friendlyFire = -1
healEnemy = -1
fallDamageTaken = -10
statueDamageTaken = 0
manualBonus = 0
victory = 100
loss = -100
tie = 0
teamSpirit = 0.5
timeScaling = 0.8

[[players]]
path = 'bot'
name = 'DerkPlayer'
test = 5

[[players]]
path = 'bot'
name = 'DerkPlayer'
test = 7