[game]
train = true
bt_best_player_name = 'lander_best_tree.json'
[bt_config]
population_size = 100
mutation_rate = 0.1
crossover_rate = 0.9
tournament_size = 5
elitism_rate = 0.1
max_depth = 3
episodes_number = 10
number_generations = 1000