[game]
best_player = 'assets/bts/frozen_lake/best.json' # path to the best bt
[bt_config]
population_size = 200 # number of individuals in the population
mutation_rate = 0.8 # probability of mutation
crossover_rate = 0.5  # probability of crossover
tournament_size = 5 # number of individuals to select for the tournament    
elitism_rate = 0.20 # percentage of the best individuals to keep in the next generation
max_depth = 30 # maximum depth of the tree in the initial population
episodes_number = 1 # number of episodes to play for each individual
number_generations = 100  # number of generations to evolve
tree_size_penalty = 0.01 # penalty for tree size
seed = 42 # random seed for gym
mutation_seed = 42 # random seed for the mutation
save_every = 1 # save the best individual every n generations
prob_keep_not_executed = 1

