[env]
name = "FrozenLake-v1"
kwargs = {}

[game]
use_wandb = true
num_iterations = 10
checkpoint_frequency = 2
evaluate_checkpoints = true
neat_config = "./configs/frozenlake/neat.ini"

winner_pickle = "./assets/weights/frozenlake_500_iterations.pickle"
gif_path = "./assets/images/neat_frozenlake_evolution.gif"
gif_checkpoints = [1, 3, 5, 7]