[env]
name = "FrozenLake-v1"
kwargs = {is_slippery = false}

[game]
use_wandb = false
num_iterations = 50
checkpoint_frequency = 1
evaluate_checkpoints = true
neat_config = "./configs/frozenlake/neat.ini"

winner_pickle = "./weights/frozenlake/frozenlake_500_iterations.pickle"
gif_path = "./weights/frozenlake/images/neat_frozenlake_evolution.gif"
gif_checkpoints = []
